version: '3'
services:
  telegram-bot:
    build: .
    environment:
    - telegramBotToken=${telegramBotToken}
    - openAiToken=${openAiToken}
    ports:
    - "${golangPort}:${golangPort}"
    networks:
    - gptbot-network

  redis:
    image: 'redis:latest'
    command: redis-server --appendfsync everysec --appendonly yes --requirepass ${redisPassword}
    restart: on-failure
    ports:
    - "${remoteRedisPort}:6379"
    volumes:
    - ./data/redis/:/data
    networks:
    - gptbot-network
networks:
  gptbot-network:
    driver: bridge
